apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ5dWdhbS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWkc5amEyVnlZM0psWkRwV1lXeGhlSGxBTVRJeiIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
